# Generated by Django 6.0.6 on 2026-06-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_classroom_class_name_remove_classroom_section_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('standard', 'division')},
        ),
    ]
