# Generated by Django 6.0.6 on 2026-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
