# Generated by Django 6.0.6 on 2026-06-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_qualification_teacher_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
