# Generated by Django 6.0.6 on 2026-06-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teacher_qualification_teacher_date_of_joining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mobile',
        ),
    ]
