# Generated by Django 6.0.6 on 2026-06-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_date_of_joining'),
        ('teachers', '0003_remove_teacher_email_remove_teacher_mobile'),
    ]

    operations = [
    ]
