# Generated by Django 6.0.6 on 2026-06-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0003_student_email_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedetail',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendancedetail',
            unique_together={('attendance', 'student')},
        ),
    ]
